topic_tools: Fix ValueErrors that occur in relay_field
There are several cases where error occurs.

Case 1: when m.header.stamp is used

rosrun topic_tools relay_field /imu/data /only_header std_msgs/Header \
'stamp: m.header.stamp
seq: m.header.seq
frame_id: imu'

This results in:

ValueError: invalid msg_args type: 1544172626663751871

because genpy.Time represents itself as an integer and not in a
dictionary form which we want (i.e. {'secs': 42, 'nsecs', 42})

Case 2: built-in function name is used for string

rosrun topic_tools relay_field /imu/data /only_header std_msgs/Header \
'stamp: now
seq: m.header.seq
frame_id: map'

This results in:

ROSSerializationException: field frame_id must be of type str

because map is a built-in function name.

Case 3: further expansion of field values is not performed

rosrun topic_tools relay_field /imu/data /imu_orientation \
geometry_msgs/QuaternionStamped \
'header: auto
quaternion: m.orientation'

This results in:

ValueError: invalid msg_args type: x: -0.03408677876
y: -0.0217779036611
z: 0.936430633068
w: -0.348513394594

because evaluating m.orientation results in a YAML string, which is not
further processed.