fix regressions from 1372 (#1473)
* make new argument optional to restore API compatibility

* Fix rosbag's internal _read_message API

* Correct return_connection_header's default value from None to False

* Add return_connection_header=False arg

... to seek_and_read_message_data_record, for BagReady102.

Otherwise we get this error (e.g. using rqt_bag):
  File ".../lib/python2.7/dist-packages/rosbag/bag.py", line 1299, in _read_message
    return self._reader.seek_and_read_message_data_record(position, raw)
    TypeError: seek_and_read_message_data_record() takes exactly 4 arguments (3 given)