Fix bag migration failures caused by typo in connection_header assignment
Bag migration failed with follwoing errors:
NameError: global name 'connection_header' is not defined
This change fixes that by using local name conn_header